//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TST.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TSTProjectEntities : DbContext
    {
        public TSTProjectEntities()
            : base("name=TSTProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<TicketStatus> TicketStatuses { get; set; }
        public virtual DbSet<TSTDepartment> TSTDepartments { get; set; }
        public virtual DbSet<TSTEmployee> TSTEmployees { get; set; }
        public virtual DbSet<TSTEmployeeStatus> TSTEmployeeStatuses { get; set; }
        public virtual DbSet<TSTTechNote> TSTTechNotes { get; set; }
        public virtual DbSet<TSTTicketPriority> TSTTicketPriorities { get; set; }
        public virtual DbSet<TSTTicket> TSTTickets { get; set; }
    }
}
